apiVersion: v1
entries:
  sample-runtime-bundle:
  - apiVersion: v1
    created: 2018-11-23T09:42:30.662482Z
    description: A Helm chart for Kubernetes
    digest: d40857774fb8c7e50d947473da628c89b1422ac375871bd8e4a2b9111f24eb85
    icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
    name: sample-runtime-bundle
    urls:
    - https://gravitonian.github.io/helm-repo/sample-runtime-bundle-0.1.0.tgz
    version: 0.1.0
generated: 2018-11-23T09:42:30.660702Z
